### ISSUE TITLE
Users can rate courses

### ISSUE THREAD

**Issue by joshuamorton** [classrank/ClassRank#18]
Users will be able to individually add information about a class they have taken. There will be an option on the user’s dashboard (the main jumping-off point for all other functions) to “add a course”. With data scraped from OSCAR, a new page with appear containing a listing of all classes in some sorted order. The user will select the class to add. A new form-page will appear to intake the user’s grade and opinions on the class. This information will then be stored in the database.

**Comment by mmanguno** [comment]
See #46
